export const GET_TEAMS = "GET_TEAMS";
export const GET_TEAMS_SUCCESS = 'GET_TEAMS_SUCCESS';
export const GET_TEAMS_ERROR = "GET_TEAMS_ERROR"

export const GET_TEAM = "GET_TEAM";
export const GET_TEAM_SUCCESS = "GET_TEAM_SUCCESS";
export const GET_TEAM_ERROR = "GET_TEAM_ERROR";

export const GET_FIXTURES_BY_LEAGUE = "GET_FIXTURES_BY_LEAGUE";
export const GET_FIXTURES_LIVE = "GET_FIXTURES_LIVE";

export const GET_EVENTS_BY_FIXTURE_SUCCESS = "GET_EVENTS_BY_FIXTURE_SUCCESS";

export const LOADING = 'LOADING';