export const GET_TEAMS_DATA = "GET_TEAMS_DATA";
export const GET_TEAM_DATA = "GET_TEAM_DATA";

export const GET_FIXTURES_BY_LEAGUE = "GET_FIXTURES_BY_LEAGUE";
export const GET_FIXTURES_LIVE = "GET_FIXTURES_LIVE";

export const GET_EVENTS_BY_FIXTURE_SUCCESS = "GET_EVENTS_BY_FIXTURE_SUCCESS";

export const LOADING = 'LOADING';