export const GET_TEAMS = "GET_TEAMS";
export const GET_TEAMS_SUCCESS = 'GET_TEAMS_SUCCESS';
export const GET_TEAMS_ERROR = "GET_TEAMS_ERROR"

export const GET_TEAM = "GET_TEAM";
export const GET_TEAM_SUCCESS = "GET_TEAM_SUCCESS";
export const GET_TEAM_ERROR = "GET_TEAM_ERROR";

export const GET_PREMIER_LEAGUE_FIXTURES = "GET_PREMIER_LEAGUE_FIXTURES";

export const GET_FIXTURES_LIVE = "GET_FIXTURES_LIVE";
export const GET_ALL_FIXTURES_LIVE = "GET_ALL_FIXTURES_LIVE";
export const GET_PREMIER_LEAGUE_FIXTURES_LIVE = "GET_PREMIER_LEAGUE_FIXTURES_LIVE";

export const GET_FIXTURES_SUCCESS = "GET_FIXTURES_SUCCESS"

export const GET_STANDINGS = "GET_STANDINGS"
export const GET_STANDINGS_SUCCESS = 'GET_STANDINGS_SUCCESS'
export const GET_STANDINGS_ERROR = 'GET_STANDINGS_ERROR'
export const LOADING_STANDINGS = 'LOADING_STANDINGS'

export const GET_EVENTS_BY_FIXTURE = "GET_EVENTS_BY_FIXTURE";
export const GET_EVENTS_BY_FIXTURE_SUCCESS = "GET_EVENTS_BY_FIXTURE_SUCCESS";

export const LOADING = 'LOADING';
